### ISSUE TITLE
Document recommended workflow

### ISSUE THREAD

**Issue by jasonkarns** [patrickjahns/chlgr#21]
I am quite intrigued by this:

> chlgr differentiates itself from other changelog actions, by managing the changelog in a separate branch and as well as maintaining and creating a pull request with the changelog.

So my understanding is that this action is intended to monitor pushes to master; after which it updates the changelog file in the release/next branch.

So is it correct that the recommended workflow is to leave the `release/next` PR open while other feature PRs are merged to master. Then when ready to bump a version, one would merge the release/next branch to master, and do a version bump + git-tag at that point?

I presume the action is smart enough to ignore the merging of the release/next branch itself?

**Comment by patrickjahns** [comment]
@jasonkarns - that is exactly the intention of this workflow.

As an example for this action, you can have a look at [ansible-role-promtail](https://github.com/patrickjahns/ansible-role-promtail) - specific the [last pull request that triggered a new changelog](https://github.com/patrickjahns/ansible-role-promtail/pull/6)

One caveat though, the action itself will not ignore merged branches, I used the normal `if` conditionals from github-actions flow.

To exclude specific commits/pull-requests:
```
    if: "!contains(github.event.head_commit.message, '[RELEASE]')"
```

For a full workflow I suggest to checkout  https://github.com/patrickjahns/ansible-role-promtail/blob/master/.github/workflows/release.yml 

The flow is split in two parts:
- merging of "normal" ( features, bugfixes etc) pull requests
  - calculate next semantic version 
  - run chlgr to create/update the changelog pr
- merging of a release pull request
  - extract the version and changelog entries from the merge commit
  - create a tag + github release with the version and the changelog entries

Let me know if this answers your open question(s). Please also let me know if you have any further suggestions for improving the documentation
